services:
  devcontainer:
    build:
      context: ./docker/devcontainer
    command:
      - sleep
      - infinity
    user: devcontainer
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
