version: '3'

silent: true

includes:
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [d]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list

  app:dev:
    cmds:
      - task: dependencies:install
      - task: run:dev
    desc: Start the application in dev mode
