version: "3"

silent: true

includes:
  back:dependencies:
    taskfile: ./taskfiles/back/dependencies.yaml
    aliases: [b:d]
  back:tests:
    taskfile: ./taskfiles/back/tests.yaml
    aliases: [b:t]
  front:dependencies:
    taskfile: ./taskfiles/front/dependencies.yaml
    aliases: [f:d]
  front:tests:
    taskfile: ./taskfiles/front/tests.yaml
    aliases: [f:t]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]

tasks:
  default:
    cmds:
      - task --list
